public  class INHeritence_child extends INHeritence_parent 
{
 public void substract()
     
 {
      integer a = 60 ;
         integer b = 40;
        integer r ;
            r = a-b;
       
        system.debug('the subtraction value is' +r);
 }
    public void multiply()
    {
      integer a = 60 ;
         integer b = 40;
        integer r ;
            r = a*b;
       
        system.debug('the multiply value is' +r);
 }
    
    
    
}