public class Sobjectclass

{
  public static void mymethod()
   
  {
     /*count a = new account ( name= 'samra' , phone= '89548');
    
    insert a;
    
   account b = new account();
    
    b.name= 'chenna';
   
    b.rating = 'warm';
    
    insert b ;
      */
      
      contact c = new contact(lastname='amazon', phone = '646265');
      
      insert c;
      
      
      contact d = new contact();
      d.lastname= 'sravas';
      d.phone  = '07568768';
      
      insert d;
      
      
  } 
    
    
}