public class While_Dowhile
{
        public static void mymethod()
     
 {
        integer i = 0;
     while(i<5)
     {
       
         system.debug('hey');
          i++;
         
     }
 }
    
       public static void mymethod1()
       {
         integer i = 0;
          
           do{
               system.debug('madhu');
               i++;
           }while(i<5);
           
           
           
       }
}